// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX_cf5ESC4EK1_18PGnUrx8tBUTEyekTU',
    appId: '1:204800026586:android:080c9eaf50dd099e9d82e3',
    messagingSenderId: '204800026586',
    projectId: 'my-car-1fb11',
    databaseURL: 'https://my-car-1fb11-default-rtdb.firebaseio.com',
    storageBucket: 'my-car-1fb11.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSukMs9pP761FOBExAWXCG1cFscQ6mB2E',
    appId: '1:204800026586:ios:c5898c5beacdac8f9d82e3',
    messagingSenderId: '204800026586',
    projectId: 'my-car-1fb11',
    databaseURL: 'https://my-car-1fb11-default-rtdb.firebaseio.com',
    storageBucket: 'my-car-1fb11.appspot.com',
    iosClientId: '204800026586-r08lqd35ra88juh6kmodt8ihqnjmc90k.apps.googleusercontent.com',
    iosBundleId: 'com.pdp.carApp',
  );
}
